numero1 = 10
numero2 = 5
numero = numero1 + numero2
print("La suma de 5 + 10 es =" ,numero)
numero = numero1 - numero2
print("La resta de 10 - 5 es =",numero)
numero = numero1 * numero2
print("La multiplicación de 10 * 5 es =",numero)
numero = numero1 / numero2
print("La división de 10 / 5 es =",numero)
numero = numero1 % numero2
print("La cotetacion es =" ,numero)